# Generated by Django 3.2.6 on 2024-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackitems', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
        migrations.AddField(
            model_name='items',
            name='estado',
            field=models.CharField(choices=[('En transito', 'Demorado'), ('Cancelado', 'Arribado')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
