# Generated by Django 3.2.6 on 2024-07-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackitems', '0002_auto_20240724_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='estado',
            field=models.CharField(choices=[('En transito', 'Demorado'), ('Cancelado', 'Arri'), ('poesia', 'Poesía')], max_length=50),
        ),
    ]
