# Generated by Django 3.2.6 on 2024-07-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackitems', '0004_auto_20240725_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='estado',
            field=models.CharField(choices=[('Arribado', 'Arribado'), ('Demorado', 'Demorado'), ('En transito', 'En transito')], max_length=50),
        ),
    ]
