# Generated by Django 3.2.6 on 2024-07-25 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackitems', '0006_auto_20240725_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='fecha_registro',
            new_name='Fecha_creacion',
        ),
        migrations.AddField(
            model_name='tracking',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
